GAS_DENSITY = 2.858
ONE_MPH = 0.44704
CLOSE_TO_ZERO_SPEED = 0.15 # Consider this 0 speed
THROTTLE_MIN = 0
THROTTLE_MAX = 1

THROTTLE_KP = .7
THROTTLE_KI = 0.
THROTTLE_KD = .05

BRAKE_STATIONARY_FORCE = 700 # Nm to keep car stationary